sudo: 'required'

language: 'generic'

# needed for the docker pipe
services:
- docker

git:
  depth: 1

before_install:
  - bash ./.travis-setup.sh
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

matrix:
  include:
    - name: "flannel"
      script: cd flannel && bash ./build.sh
    - name: "kubernetes-dashboard"
      script: cd kubernetes-dashboard && bash ./build.sh
    - name: "prometheus-node-exporter"
      script: cd prometheus-node-exporter && bash ./build.sh
    - name: "tiller"
      script: cd tiller && bash ./build.sh
