language: python
python:
  - "3.6"

# needed for the docker pipe
services:
- docker

git:
  depth: 1

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_LOGIN" --password-stdin

matrix:
  include:
    - name: "flannel"
      python: "3.6"
      script: bash ./flannel/build.sh
    - name: "kubernetes-dashboard"
      python: "3.6"
      script: bash ./kubernetes-dashboard/build.sh
    - name: "prometheus-node-exporter"
      python: "3.6"
      script: bash ./prometheus-node-exporter/build.sh
    - name: "tiller"
      python: "3.6"
      script: bash ./tiller/build.sh
