sudo: 'required'

language: python
python:
  - "3.6"

# needed for the docker pipe
services:
- docker

env:
  - DOCKER_CLI_EXPERIMENTAL=enabled

git:
  depth: 1

before_install:
#  - bash ./.travis-setup.sh
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

matrix:
  include:
    - name: "flannel"
      script: bash ./flannel/build.sh
    - name: "kubernetes-dashboard"
      script: bash ./kubernetes-dashboard/build.sh
    - name: "prometheus-node-exporter"
      script: bash ./prometheus-node-exporter/build.sh
    - name: "tiller"
      script: bash ./tiller/build.sh
