sudo: 'required'

language: python
python:
  - "3.6"

# needed for the docker pipe
services:
- docker

env:
  global:
    - QEMU_VERSION=v3.1.0-2
    - DOCKER_CLI_EXPERIMENTAL=enabled

git:
  depth: 1

before_install:
  - bash ./.travis-setup.sh
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

matrix:
  include:
    - name: "flannel"
      script: cd flannel && bash ./build.sh
    - name: "flannel-cni"
      script: cd flannel-cni && bash ./build.sh      
    - name: "prometheus-server"
      script: cd prometheus-server && bash ./build.sh
    - name: "prometheus-node-exporter"
      script: cd prometheus-node-exporter && bash ./build.sh
    - name: "prometheus-blackbox-exporter"
      script: cd prometheus-blackbox-exporter && bash ./build.sh
    - name: "prometheus-snmp-exporter"
      script: cd prometheus-snmp-exporter && bash ./build.sh
    - name: "prometheus-alertmanager"
      script: cd prometheus-alertmanager && bash ./build.sh
    - name: "prometheus-pushgateway"
      script: cd prometheus-pushgateway && bash ./build.sh
    - name: "tiller"
      script: cd tiller && bash ./build.sh
    - name: "cni-plugins"
      script: cd cni-plugins && bash ./build.sh
    - name: "matchbox"
      script: cd matchbox && bash ./build.sh
