sudo: 'required'

language: python
python:
  - "3.6"

# needed for the docker pipe
services:
- docker

env:
  - DOCKER_CLI_EXPERIMENTAL=enabled

git:
  depth: 1

before_install:
  - bash ./.travis-setup.sh
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

matrix:
  include:
    - name: "flannel"
      script: cd flannel && bash ./build.sh
    - name: "kubernetes-dashboard"
      script: cd kubernetes-dashboard && bash ./build.sh
    - name: "prometheus-node-exporter"
      script: cd prometheus-node-exporter && bash ./build.sh
    - name: "tiller"
      script: cd tiller && bash ./build.sh
    - name: "tiller-test-arm"
      os: linux
      dist: trusty
      env:
        - ARCH="armv8"
      script: cd tiller && bash ./build-arm.sh
